// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

import { env } from "process";


// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

// export const environment = {
//   production: false,
//   version: '1.0.0' + '-dev',
//   serverUrl: '/api',
//   defaultLanguage: 'en-US',
//   supportedLanguages: ['en-US'],
// };

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  // secureRoutes: ['https://my-second-secure-url.com/', 'https://devkit-api-employeeprofile.azurewebsites.net/api'],
  stsServer: 'https://localhost:5005',
  clientId: 'procurementAngularClient',
  scope: 'openid profile',
  // Api_Endpoint: 'https://devkit-api-employeeprofile.azurewebsites.net/api/v1',
  // Api_Mock_Endpoint: 'https://devkit-api-employeeprofile.azurewebsites.net/api/v1',
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
